package forge.gui;

import java.util.concurrent.Semaphore;

import forge.util.ThreadUtil;

public class FThreads {
    private FThreads() { } // no instances supposed

    /** Checks if calling method uses event dispatch thread.
     * Exception thrown if method is on "wrong" thread.
     * A boolean is passed to indicate if the method must be EDT or not.
     *
     * @param methodName &emsp; String, part of the custom exception message.
     * @param mustBeEDT &emsp; boolean: true = exception if not EDT, false = exception if EDT
     */
    public static void assertExecutedByEdt(final boolean mustBeEDT) {
        if (GuiBase.isNetworkplay(null))
            return; //don't check for networkplay
        if (isGuiThread() != mustBeEDT) {
            final StackTraceElement[] trace = Thread.currentThread().getStackTrace();
            final String methodName = trace[2].getClassName() + "." + trace[2].getMethodName();
            final String modalOperator = mustBeEDT ? " must be" : " may not be";
            throw new IllegalStateException(methodName + modalOperator + " accessed from the event dispatch thread.");
        }
    }

    public static void invokeInEdtLater(final Runnable proc) {
        GuiBase.getInterface().invokeInEdtLater(proc);
    }

    public static void invokeInEdtNowOrLater(final Runnable proc) {
        if (isGuiThread()) {
            GuiBase.getInterface().invokeInEdtNow(proc);
        } else {
            GuiBase.getInterface().invokeInEdtLater(proc);
        }
    }

    /**
     * Invoke the given Runnable in an Event Dispatch Thread and wait for it to
     * finish; but <B>try to use SwingUtilities.invokeLater instead whenever
     * feasible.</B>
     *
     * Exceptions generated by SwingUtilities.invokeAndWait (if used), are
     * rethrown as RuntimeExceptions.
     *
     * @param proc
     *            the Runnable to run
     * @see fgd.SwingUtilities#invokeLater(Runnable)
     */
    public static void invokeInEdtAndWait(final Runnable proc) {
        GuiBase.getInterface().invokeInEdtAndWait(proc);
    }

    private static int backgroundThreadCount;
    public static void invokeInBackgroundThread(final Runnable proc) {
        //start thread name with "Game" so isGuiThread() returns false on GuiMobile
        new Thread(proc, "Game BT" + backgroundThreadCount).start();
        backgroundThreadCount++;
    }

    // ── EDT-posting throttle ─────────────────────────────────────────────────
    // A platform (e.g. iOS) can call configureEdtThrottle(new Semaphore(N))
    // once at startup to impose back-pressure on background threads that
    // generate work to be posted to the EDT.  Callers bracket their work with
    // acquireEdtThrottle() / releaseEdtThrottle(); both are no-ops when no
    // semaphore has been configured (the default on all other platforms).

    private static volatile Semaphore edtThrottleSemaphore = null;

    /**
     * Install a semaphore that bounds the number of EDT-bound work items that
     * may be in flight simultaneously.  Pass {@code null} to remove throttling.
     * Must be called before any background threads are started.
     */
    public static void configureEdtThrottle(final Semaphore semaphore) {
        edtThrottleSemaphore = semaphore;
    }

    /**
     * Acquire one permit from the configured EDT throttle semaphore, blocking
     * until a permit is available.  No-op if no semaphore has been configured.
     * Restores the interrupted status and returns immediately on interruption.
     */
    public static void acquireEdtThrottle() {
        final Semaphore s = edtThrottleSemaphore;
        if (s == null) { return; }
        try {
            s.acquire();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    /**
     * Release one permit back to the configured EDT throttle semaphore.
     * No-op if no semaphore has been configured.
     */
    public static void releaseEdtThrottle() {
        final Semaphore s = edtThrottleSemaphore;
        if (s != null) { s.release(); }
    }

    public static boolean isGuiThread() {
        return GuiBase.getInterface().isGuiThread();
    }

    public static void delayInEDT(final int milliseconds, final Runnable inputUpdater) {
        final Runnable runInEdt = () -> FThreads.invokeInEdtNowOrLater(inputUpdater);
        ThreadUtil.delay(milliseconds, runInEdt);
    }

    public static String debugGetCurrThreadId() {
        return isGuiThread() ? "EDT" : Thread.currentThread().getName();
    }

    public static String debugGetStackTraceItem(final int depth, final boolean shorter) {
        final StackTraceElement[] trace = Thread.currentThread().getStackTrace();
        String lastItem = trace[depth].toString();
        if (shorter) {
            int lastPeriod = lastItem.lastIndexOf('.');
            lastPeriod = lastItem.lastIndexOf('.', lastPeriod-1);
            lastPeriod = lastItem.lastIndexOf('.', lastPeriod-1);
            lastItem = lastItem.substring(lastPeriod+1);
            return String.format("%s > from %s", debugGetCurrThreadId(), lastItem);
        }
        return String.format("%s > %s called from %s", debugGetCurrThreadId(),
                trace[2].getClassName() + "." + trace[2].getMethodName(), lastItem);
    }

    public static String debugGetStackTraceItem(final int depth) {
        return debugGetStackTraceItem(depth, false);
    }
}
