import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

/**
 * Bytecode-level scanner that finds all calls to Java 9-11 API additions on
 * existing JDK classes.  Unlike source-level grep, this finds issues in
 * compiler-generated synthetic methods, lambda helper classes, enum clinit
 * blocks, and any other auto-generated bytecode that does not appear verbatim
 * in the source files.
 *
 * <p>The scanner checks each {@code INVOKEVIRTUAL}, {@code INVOKESTATIC}, and
 * {@code INVOKEINTERFACE} instruction against a curated database of Java 9-11
 * API additions on existing JDK classes, then categorises each hit as:
 *
 * <ul>
 *   <li><b>PATCHED</b>  — already rewritten at build time by StreamDesugar.java
 *       (patterns 49-60).  These are safe on iOS.</li>
 *   <li><b>CLAIMED</b>  — explicitly listed in {@code scripts/build-java-stubs.sh}
 *       as natively provided by robovmx's robovm-rt.  Should be safe; listed for
 *       awareness and as a cross-check (recall that {@code Predicate.not} crashed
 *       despite a broad "java.util.function.*" claim, so named-method claims are
 *       more trustworthy than package-level ones).</li>
 *   <li><b>RISK:HIGH</b> — NOT patched by StreamDesugar, NOT explicitly claimed by
 *       robovmx.  If any of these call sites are reachable at runtime on iOS they
 *       will throw {@code NoSuchMethodError}.  Add a StreamDesugar pattern +
 *       StreamUtil helper for each one found in a live code path.</li>
 * </ul>
 *
 * <h2>Usage</h2>
 * <pre>
 *   java -cp asm.jar:. ApiScan &lt;dir|jar&gt; [&lt;dir2|jar2&gt; ...]
 * </pre>
 * Or via {@code scripts/ios-bytecode-scan.sh} which compiles this class and
 * runs it automatically after {@code mvn compile}.
 *
 * <h2>Coverage</h2>
 * Java 9 additions: Optional.or/ifPresentOrElse/stream, Stream.ofNullable/
 * takeWhile/dropWhile/iterate(3-arg), InputStream.readAllBytes/readNBytes/
 * transferTo, Map.entry/ofEntries, Objects.requireNonNullElse/ElseGet.
 *
 * Java 10 additions: Optional.orElseThrow() (no-arg), Collectors.toUnmodifiable*.
 *
 * Java 11 additions: Predicate.not, String.isBlank/repeat/strip/lines,
 * Optional.isEmpty, Collection.toArray(IntFunction), Path.of, Files.readString/
 * writeString.
 */
public class ApiScan {

    enum Category { PATCHED, CLAIMED, RISK_HIGH }

    static final class ApiEntry {
        final String owner;
        final String name;
        final String desc;          // null = match any descriptor with this name
        final int javaVersion;
        final Category category;
        final String description;   // human-readable label for the report

        ApiEntry(String owner, String name, String desc,
                 int javaVersion, Category category, String description) {
            this.owner       = owner;
            this.name        = name;
            this.desc        = desc;
            this.javaVersion = javaVersion;
            this.category    = category;
            this.description = description;
        }

        /** Key used for deduplication: owner + name + desc (or owner + name if no desc). */
        String key() {
            return desc != null ? owner + '.' + name + desc : owner + '.' + name + "(*)";
        }
    }

    // ── API database ──────────────────────────────────────────────────────────

    static final List<ApiEntry> APIS = new ArrayList<>();

    static {
        // ── Java 9 additions ──────────────────────────────────────────────────

        add("java/util/Optional", "or",
            "(Ljava/util/function/Supplier;)Ljava/util/Optional;",
            9, Category.RISK_HIGH, "Optional.or(Supplier) — Java 9");
        add("java/util/Optional", "ifPresentOrElse",
            "(Ljava/util/function/Consumer;Ljava/lang/Runnable;)V",
            9, Category.RISK_HIGH, "Optional.ifPresentOrElse(Consumer,Runnable) — Java 9");
        add("java/util/Optional", "stream",
            "()Ljava/util/stream/Stream;",
            9, Category.RISK_HIGH, "Optional.stream() — Java 9");

        add("java/util/stream/Stream", "ofNullable",
            "(Ljava/lang/Object;)Ljava/util/stream/Stream;",
            9, Category.RISK_HIGH, "Stream.ofNullable(T) — Java 9");
        add("java/util/stream/Stream", "takeWhile",
            "(Ljava/util/function/Predicate;)Ljava/util/stream/Stream;",
            9, Category.RISK_HIGH, "Stream.takeWhile(Predicate) — Java 9");
        add("java/util/stream/Stream", "dropWhile",
            "(Ljava/util/function/Predicate;)Ljava/util/stream/Stream;",
            9, Category.RISK_HIGH, "Stream.dropWhile(Predicate) — Java 9");
        // 3-arg iterate (Java 9); the 2-arg version is Java 8 (safe).
        add("java/util/stream/Stream", "iterate",
            "(Ljava/lang/Object;Ljava/util/function/Predicate;Ljava/util/function/UnaryOperator;)Ljava/util/stream/Stream;",
            9, Category.RISK_HIGH, "Stream.iterate(seed,Predicate,UnaryOperator) — Java 9 (3-arg)");

        add("java/io/InputStream", "readAllBytes",
            "()[B",
            9, Category.RISK_HIGH, "InputStream.readAllBytes() — Java 9");
        add("java/io/InputStream", "transferTo",
            "(Ljava/io/OutputStream;)J",
            9, Category.RISK_HIGH, "InputStream.transferTo(OutputStream) — Java 9");

        add("java/util/Map", "entry",
            "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map$Entry;",
            9, Category.RISK_HIGH, "Map.entry(K,V) — Java 9");
        add("java/util/Map", "ofEntries",
            "([Ljava/util/Map$Entry;)Ljava/util/Map;",
            9, Category.RISK_HIGH, "Map.ofEntries(Map.Entry...) — Java 9");

        // Explicitly listed by name in build-java-stubs.sh as provided by robovmx.
        add("java/util/Objects", "requireNonNullElse",
            "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
            9, Category.CLAIMED, "Objects.requireNonNullElse(T,T) — Java 9 [claimed by robovmx]");
        add("java/util/Objects", "requireNonNullElseGet",
            "(Ljava/lang/Object;Ljava/util/function/Supplier;)Ljava/lang/Object;",
            9, Category.CLAIMED, "Objects.requireNonNullElseGet(T,Supplier) — Java 9 [claimed by robovmx]");

        // ── Java 10 additions ─────────────────────────────────────────────────

        // no-arg orElseThrow() is Java 10; the supplier version orElseThrow(Supplier) is Java 8.
        add("java/util/Optional", "orElseThrow",
            "()Ljava/lang/Object;",
            10, Category.RISK_HIGH, "Optional.orElseThrow() no-arg — Java 10");

        add("java/util/stream/Collectors", "toUnmodifiableList",
            "()Ljava/util/stream/Collector;",
            10, Category.RISK_HIGH, "Collectors.toUnmodifiableList() — Java 10");
        add("java/util/stream/Collectors", "toUnmodifiableSet",
            "()Ljava/util/stream/Collector;",
            10, Category.RISK_HIGH, "Collectors.toUnmodifiableSet() — Java 10");
        add("java/util/stream/Collectors", "toUnmodifiableMap",
            "(Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;",
            10, Category.RISK_HIGH, "Collectors.toUnmodifiableMap(F,F) — Java 10");
        add("java/util/stream/Collectors", "toUnmodifiableMap",
            "(Ljava/util/function/Function;Ljava/util/function/Function;Ljava/util/function/BinaryOperator;)Ljava/util/stream/Collector;",
            10, Category.RISK_HIGH, "Collectors.toUnmodifiableMap(F,F,BinaryOp) — Java 10");

        // ── Java 11 additions ─────────────────────────────────────────────────

        // PATCHED by StreamDesugar Pattern 58.
        add("java/util/function/Predicate", "not",
            "(Ljava/util/function/Predicate;)Ljava/util/function/Predicate;",
            11, Category.PATCHED, "Predicate.not(Predicate) — Java 11 [StreamDesugar P58]");

        // CLAIMED by robovmx (build-java-stubs.sh) AND defensively patched P59.
        add("java/lang/String", "isBlank",
            "()Z",
            11, Category.CLAIMED, "String.isBlank() — Java 11 [claimed + StreamDesugar P59]");
        // CLAIMED by robovmx AND defensively patched P60.
        add("java/lang/String", "repeat",
            "(I)Ljava/lang/String;",
            11, Category.CLAIMED, "String.repeat(int) — Java 11 [claimed + StreamDesugar P60]");

        // Not in robovmx's claimed list (only isBlank/repeat/codePoints/join are listed).
        add("java/lang/String", "strip",
            "()Ljava/lang/String;",
            11, Category.RISK_HIGH, "String.strip() — Java 11");
        add("java/lang/String", "stripLeading",
            "()Ljava/lang/String;",
            11, Category.RISK_HIGH, "String.stripLeading() — Java 11");
        add("java/lang/String", "stripTrailing",
            "()Ljava/lang/String;",
            11, Category.RISK_HIGH, "String.stripTrailing() — Java 11");
        add("java/lang/String", "lines",
            "()Ljava/util/stream/Stream;",
            11, Category.RISK_HIGH, "String.lines() — Java 11");

        // readNBytes(int) is Java 11; readNBytes(byte[],int,int) is Java 9.
        add("java/io/InputStream", "readNBytes",
            "(I)[B",
            11, Category.RISK_HIGH, "InputStream.readNBytes(int) — Java 11");

        // CLAIMED by robovmx.
        add("java/util/Optional", "isEmpty",
            "()Z",
            11, Category.CLAIMED, "Optional.isEmpty() — Java 11 [claimed by robovmx]");

        // Collection.toArray(IntFunction) is Java 11.
        // NOTE: Stream.toArray(IntFunction) is Java 8 (different owner) — not scanned here.
        add("java/util/Collection", "toArray",
            "(Ljava/util/function/IntFunction;)[Ljava/lang/Object;",
            11, Category.RISK_HIGH, "Collection.toArray(IntFunction) — Java 11");

        // Path.of(String, String...) is Java 11; similar to Paths.get but not NIO-patched.
        add("java/nio/file/Path", "of",
            "(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;",
            11, Category.RISK_HIGH, "Path.of(String,String...) — Java 11 (like Paths.get; add P51 variant)");

        add("java/nio/file/Files", "readString",
            "(Ljava/nio/file/Path;)Ljava/lang/String;",
            11, Category.RISK_HIGH, "Files.readString(Path) — Java 11");
        add("java/nio/file/Files", "readString",
            "(Ljava/nio/file/Path;Ljava/nio/charset/Charset;)Ljava/lang/String;",
            11, Category.RISK_HIGH, "Files.readString(Path,Charset) — Java 11");
        add("java/nio/file/Files", "writeString",
            "(Ljava/nio/file/Path;Ljava/lang/CharSequence;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;",
            11, Category.RISK_HIGH, "Files.writeString(Path,CharSequence,OpenOption...) — Java 11");
        add("java/nio/file/Files", "writeString",
            "(Ljava/nio/file/Path;Ljava/lang/CharSequence;Ljava/nio/charset/Charset;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;",
            11, Category.RISK_HIGH, "Files.writeString(Path,CharSequence,Charset,OpenOption...) — Java 11");

        // ── Java 9 CompletableFuture additions ────────────────────────────────

        // PATCHED by StreamDesugar Pattern 61.
        // The no-executor variant routes to ForkJoinPool.commonPool(); ForkJoinWorkerThread.<clinit>
        // reflects on Thread.threadLocals which is absent from robovmx's robovm-rt.
        add("java/util/concurrent/CompletableFuture", "supplyAsync",
            "(Ljava/util/function/Supplier;)Ljava/util/concurrent/CompletableFuture;",
            8, Category.PATCHED,
            "CompletableFuture.supplyAsync(Supplier) — ForkJoinPool crash on iOS [StreamDesugar P61]");

        // PATCHED by StreamDesugar Pattern 62.
        // completeOnTimeout(T, long, TimeUnit) is Java 9; absent from robovmx's CF.
        add("java/util/concurrent/CompletableFuture", "completeOnTimeout",
            "(Ljava/lang/Object;JLjava/util/concurrent/TimeUnit;)Ljava/util/concurrent/CompletableFuture;",
            9, Category.PATCHED,
            "CompletableFuture.completeOnTimeout(T,long,TimeUnit) — Java 9 [StreamDesugar P62]");

        // PATCHED by StreamDesugar Pattern 63.
        // parallelStream() routes to ForkJoinPool.commonPool(); ForkJoinWorkerThread.<clinit>
        // reflects on Thread.threadLocals which is absent from robovmx's robovm-rt.
        add("java/util/Collection", "parallelStream",
            "()Ljava/util/stream/Stream;",
            8, Category.PATCHED,
            "Collection.parallelStream() — ForkJoinPool crash on iOS [StreamDesugar P63]");
        add("java/util/List", "parallelStream",
            "()Ljava/util/stream/Stream;",
            8, Category.PATCHED,
            "List.parallelStream() — ForkJoinPool crash on iOS [StreamDesugar P63]");
    }

    private static void add(String owner, String name, String desc,
                             int ver, Category cat, String description) {
        APIS.add(new ApiEntry(owner, name, desc, ver, cat, description));
    }

    // ── Lookup map: owner → name → list<ApiEntry> ─────────────────────────────

    /**
     * Maps {@code owner} → {@code name} → list of candidates.
     * We keep a list because some methods have multiple overloads at different Java versions.
     */
    static final Map<String, Map<String, List<ApiEntry>>> LOOKUP = new LinkedHashMap<>();

    static {
        for (ApiEntry e : APIS) {
            LOOKUP.computeIfAbsent(e.owner, k -> new LinkedHashMap<>())
                  .computeIfAbsent(e.name, k -> new ArrayList<>())
                  .add(e);
        }
    }

    // ── Hit accumulator ───────────────────────────────────────────────────────

    /**
     * Tracks occurrences of a scanned API call site:
     * the ApiEntry plus a list of "className:methodName" locations.
     */
    static final class HitGroup {
        final ApiEntry api;
        final List<String> locations = new ArrayList<>();
        HitGroup(ApiEntry api) { this.api = api; }
    }

    /** key() → HitGroup, preserving insertion order. */
    static final Map<String, HitGroup> HITS = new LinkedHashMap<>();

    // ── Entry point ───────────────────────────────────────────────────────────

    public static void main(String[] args) throws IOException {
        if (args.length == 0) {
            System.err.println("Usage: ApiScan <dir|jar> [<dir2|jar2> ...]");
            System.exit(1);
        }
        for (String arg : args) {
            Path p = Paths.get(arg);
            if (Files.isDirectory(p)) {
                scanDirectory(p);
            } else if (Files.isRegularFile(p) && arg.endsWith(".jar")) {
                scanJar(p);
            } else {
                System.err.println("[ApiScan] skipping '" + arg + "' (not a directory or .jar)");
            }
        }
        printReport();
    }

    // ── Directory traversal ───────────────────────────────────────────────────

    private static void scanDirectory(Path dir) throws IOException {
        Files.walkFileTree(dir, new SimpleFileVisitor<Path>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                if (file.toString().endsWith(".class")) {
                    byte[] bytes = Files.readAllBytes(file);
                    scanClass(bytes, dir.toString());
                }
                return FileVisitResult.CONTINUE;
            }
        });
    }

    private static void scanJar(Path jar) throws IOException {
        try (JarFile jf = new JarFile(jar.toFile())) {
            Enumeration<JarEntry> entries = jf.entries();
            while (entries.hasMoreElements()) {
                JarEntry entry = entries.nextElement();
                if (entry.getName().endsWith(".class")) {
                    try (InputStream in = jf.getInputStream(entry)) {
                        byte[] bytes = readAllBytes(in);
                        scanClass(bytes, jar.getFileName().toString());
                    }
                }
            }
        }
    }

    /** Java-8-compatible equivalent of {@code InputStream.readAllBytes()} (Java 9). */
    private static byte[] readAllBytes(InputStream in) throws IOException {
        byte[] buf = new byte[8192];
        java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
        int n;
        while ((n = in.read(buf)) > 0) baos.write(buf, 0, n);
        return baos.toByteArray();
    }

    // ── Per-class scan ────────────────────────────────────────────────────────

    private static void scanClass(byte[] classBytes, String source) {
        ClassReader reader = new ClassReader(classBytes);
        reader.accept(new ClassVisitor(Opcodes.ASM9) {
            private String currentClass;

            @Override
            public void visit(int version, int access, String name, String signature,
                              String superName, String[] interfaces) {
                currentClass = name;
            }

            @Override
            public MethodVisitor visitMethod(int access, String mName, String mDesc,
                                              String signature, String[] exceptions) {
                return new MethodVisitor(Opcodes.ASM9) {
                    @Override
                    public void visitMethodInsn(int opcode, String owner, String name,
                                                String descriptor, boolean isInterface) {
                        checkCall(owner, name, descriptor, currentClass + "." + mName);
                    }
                };
            }
        }, ClassReader.SKIP_FRAMES);
    }

    private static void checkCall(String owner, String name, String descriptor, String location) {
        Map<String, List<ApiEntry>> byName = LOOKUP.get(owner);
        if (byName == null) return;
        List<ApiEntry> candidates = byName.get(name);
        if (candidates == null) return;
        for (ApiEntry e : candidates) {
            if (e.desc == null || e.desc.equals(descriptor)) {
                String key = e.key();
                HITS.computeIfAbsent(key, k -> new HitGroup(e)).locations.add(location);
                return; // one match per instruction is enough
            }
        }
    }

    // ── Report ────────────────────────────────────────────────────────────────

    private static void printReport() {
        // Sort hits by category then java version then description
        Map<Category, List<HitGroup>> byCategory = new TreeMap<>(
                (a, b) -> a.ordinal() - b.ordinal());
        for (Category c : Category.values()) {
            byCategory.put(c, new ArrayList<>());
        }
        for (HitGroup hg : HITS.values()) {
            byCategory.get(hg.api.category).add(hg);
        }

        int riskCount = byCategory.get(Category.RISK_HIGH).stream()
                                  .mapToInt(hg -> hg.locations.size()).sum();

        printDivider();
        System.out.println(" iOS Bytecode API Scan — Java 9-11 call sites in compiled classes");
        System.out.println(" Scans for method calls that will NoSuchMethodError on iOS if not");
        System.out.println(" patched by StreamDesugar or natively provided by robovmx robovm-rt.");
        printDivider();
        System.out.println();
        System.out.printf(" Summary: %d RISK:HIGH call sites, %d CLAIMED, %d PATCHED%n%n",
                riskCount,
                byCategory.get(Category.CLAIMED).stream().mapToInt(hg -> hg.locations.size()).sum(),
                byCategory.get(Category.PATCHED).stream().mapToInt(hg -> hg.locations.size()).sum());

        printSection("RISK:HIGH — NOT patched, NOT claimed; action required if reachable on iOS",
                byCategory.get(Category.RISK_HIGH), "RISK");
        printSection("CLAIMED  — listed as provided by robovmx robovm-rt (should be safe)",
                byCategory.get(Category.CLAIMED), "CLAIMED");
        printSection("PATCHED  — rewritten at build time by StreamDesugar.java (safe)",
                byCategory.get(Category.PATCHED), "PATCHED");

        printDivider();
        if (riskCount > 0) {
            System.out.println(" ACTION: " + riskCount + " RISK:HIGH call site(s) found.");
            System.out.println(" For each one in a live iOS code path:");
            System.out.println("   1. Add a pattern to scripts/StreamDesugar.java");
            System.out.println("   2. Add a helper method to forge-core/.../forge/util/StreamUtil.java");
            System.out.println("   3. Re-run scripts/desugar-streams.sh");
        } else {
            System.out.println(" No RISK:HIGH call sites found — all Java 9-11 APIs are patched or claimed.");
        }
        printDivider();
    }

    private static void printSection(String title, List<HitGroup> groups, String label) {
        System.out.println("────────────────────────────────────────────────────────────────────────────────");
        System.out.println(" " + label + ": " + title);
        System.out.println("────────────────────────────────────────────────────────────────────────────────");
        if (groups.isEmpty()) {
            System.out.println("  (none found)");
        } else {
            for (HitGroup hg : groups) {
                System.out.printf("  [Java %d] %s%n", hg.api.javaVersion, hg.api.description);
                System.out.printf("           %d call site(s):%n", hg.locations.size());
                for (String loc : hg.locations) {
                    System.out.println("    " + loc.replace('/', '.'));
                }
            }
        }
        System.out.println();
    }

    private static void printDivider() {
        System.out.println("════════════════════════════════════════════════════════════════════════════════");
    }
}
