name: Test build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17', '21']
    name: Test with Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Install virtual framebuffer (if not available) to allow running GUI on a headless server
        run: command -v Xvfb >/dev/null 2>&1 || { sudo apt update && sudo apt install -y xvfb; }

      - name: Run tests in virtual framebuffer
        run: |
          export DISPLAY=":1"
          Xvfb :1 -screen 0 800x600x8 &
          mvn -U -B clean test

  build-ios:
    runs-on: macos-latest
    permissions:
      contents: read
    name: Test iOS build with Java 17
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Clone robovmx
        run: git clone --depth 1 --branch experiment/2-libcore-10 https://github.com/robovmx/robovmx.git robovmx

      - name: Install robovmx to local Maven repository
        run: |
          cd robovmx
          mvn install -Dmaven.test.skip=true

      - name: Build forge-gui-ios
        run: mvn -U -B -pl forge-gui-ios -am install -Dmaven.test.skip=true
