package forge.teavm;

import com.github.xpenatan.gdx.teavm.backends.shared.config.AssetFileHandle;
import com.github.xpenatan.gdx.teavm.backends.shared.config.compiler.TeaCompiler;
import org.teavm.vm.TeaVMOptimizationLevel;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

/**
 * Build-time driver that invokes the gdx-teavm {@link TeaCompiler} to
 * cross-compile the Forge mobile UI from JVM bytecode into JavaScript for
 * browser deployment.
 *
 * <p>This class runs on the <em>host JVM</em> during the Maven {@code package}
 * phase (triggered by {@code exec-maven-plugin} with the {@code -Pteavm}
 * profile).  It is <strong>not</strong> compiled into the browser bundle – only
 * {@link TeaVMLauncher} and the classes it reaches are transpiled.
 *
 * <h2>Usage</h2>
 * <pre>
 *   mvn -pl forge-gui-teavm -Pteavm package
 * </pre>
 *
 * <h2>Output layout</h2>
 * <pre>
 *   target/dist/webapp/
 *     index.html          – host page generated by WebBackend
 *     app.js              – transpiled game code
 *     scripts/
 *       gdx.wasm.js       – LibGDX native code (Emscripten)
 *       howler.js         – Web Audio library
 *     assets/             – game resources (copied from assetsDir)
 * </pre>
 *
 * <h2>Iterative debug loop</h2>
 * <ol>
 *   <li>Run this build ({@code mvn -Pteavm package}).</li>
 *   <li>Fix TeaVM compilation errors (typically: missing stubs in
 *       {@code src/main/java/}; see {@link TeaVMAdapter} for the pattern).</li>
 *   <li>Run the smoke test ({@code mvn -Pteavm integration-test}) to verify the
 *       home screen loads in a headless Chromium browser.</li>
 *   <li>Repeat.</li>
 * </ol>
 */
public class BuildForgeTeaVM {

    public static void main(String[] args) throws IOException {
        /*
         * Path to the Forge assets directory.  The TeaCompiler copies everything
         * under this path into the output webapp/assets/ folder.
         *
         * For a local dev build, resources live in forge-gui/:
         *   assetsDir = "../forge-gui"
         *
         * For CI / release, parameterise via system property:
         *   mvn -Dforge.assetsDir=/path/to/assets -Pteavm package
         *
         * NOTE: The full Forge asset set is multi-gigabyte.  For early
         * development, use a minimal asset set (base skin + core card data only).
         * A CDN / lazy-loading strategy is needed for production deployment.
         */
        String assetsDir = System.getProperty("forge.assetsDir", "../forge-gui");

        /*
         * Output directory.  Defaults to "target/dist" relative to the current
         * working directory.  When run via the exec-maven-plugin from the project
         * root, the system property forge.buildDir is set to the module's
         * ${project.build.directory} (e.g. forge-gui-teavm/target) so output
         * lands in the correct module directory rather than the root target/.
         */
        String buildDir = System.getProperty("forge.buildDir", "target");
        File outputDir = new File(buildDir, "dist");

        /*
         * Use ForgeWebBackend instead of bare WebBackend.  ForgeWebBackend
         * overrides setup() to call tool.setStrict(false), which downgrades
         * "missing class/method" diagnostics from hard errors to warnings for
         * code paths that are dead in the browser (Guava caches, threading,
         * java.util.concurrent, javax.xml, etc.).
         */
        ForgeWebBackend backend = new ForgeWebBackend();
        backend.setHtmlTitle("Forge \u2013 Magic: The Gathering");
        // width=0, height=0 → canvas fills the browser window
        backend.setHtmlWidth(0);
        backend.setHtmlHeight(0);
        /*
         * In development: set true to automatically start embedded Jetty
         * after compilation so the game can be tested immediately at
         * http://localhost:8080/.
         *
         * In CI / for HomeScreenLoadTest: set false – the test starts its
         * own HTTP server on a random port.
         */
        backend.setStartJettyAfterBuild(false);

        new TeaCompiler(backend)
                .addAssets(new AssetFileHandle(assetsDir))
                .setMainClass(TeaVMLauncher.class.getName())
                /*
                 * SIMPLE optimisation: faster builds, readable stack traces.
                 * Switch to ADVANCED for release (smaller JS, harder to debug).
                 */
                .setOptimizationLevel(TeaVMOptimizationLevel.SIMPLE)
                .setObfuscated(false)
                .build(outputDir);

        /*
         * Copy gdx-teavm runtime scripts to webapp/scripts/.
         *
         * The gdx-teavm WebBackend expects gdx.wasm.js and howler.js to be
         * served from /scripts/ relative to the page root.  These files live
         * inside the backend-web JAR (at its root, not under a package path)
         * and must be explicitly copied out since WebBackend's automatic
         * resource-scanning mechanism doesn't pick them up when running via
         * exec-maven-plugin (it relies on META-INF/gdx-teavm.properties
         * resource path patterns that don't match the JAR's root-level files).
         */
        copyRuntimeScripts(new File(outputDir, "webapp/scripts"));

        /*
         * Regenerate preload.txt so it always contains valid entries.
         *
         * gdx-teavm's asset loader reads webapp/assets/preload.txt at runtime
         * to discover which assets to download.  Each line must have exactly 5
         * colon-separated fields:
         *
         *   {fileType}:{assetType}:{path}:{sizeBytes}:{overwrite}
         *
         * When the TeaCompiler doesn't find any assets to copy (e.g. because
         * the assetsDir path isn't reachable from the working directory during
         * the Maven build), it generates an empty preload.txt which is
         * rejected by the parser with "Invalid assets description file. 1".
         *
         * We regenerate the file by scanning the actual webapp/assets/ output
         * directory after the build, so at minimum startup-logo.png (copied
         * from the backend-web JAR) is listed.
         */
        regeneratePreloadTxt(new File(outputDir, "webapp/assets"));
    }

    /**
     * Copies {@code gdx.wasm.js} and {@code howler.js} from the
     * {@code backend-web} JAR (which ships them as root-level classpath
     * resources) into {@code scriptsDir}, creating it if necessary.
     */
    private static void copyRuntimeScripts(File scriptsDir) throws IOException {
        scriptsDir.mkdirs();
        for (String resource : new String[]{"gdx.wasm.js", "howler.js"}) {
            URL url = BuildForgeTeaVM.class.getClassLoader().getResource(resource);
            if (url == null) {
                System.err.println("[BuildForgeTeaVM] WARNING: runtime script not found on classpath: " + resource);
                continue;
            }
            File dest = new File(scriptsDir, resource);
            try (InputStream in = url.openStream()) {
                Files.copy(in, dest.toPath(), StandardCopyOption.REPLACE_EXISTING);
                System.out.println("[BuildForgeTeaVM] Copied " + resource + " → " + dest);
            }
        }
    }

    /**
     * Regenerates {@code preload.txt} inside {@code assetsDir} by scanning all
     * regular files in that directory tree.
     *
     * <p>The format expected by {@code AssetLoadImpl$5.onSuccess()} is:
     * <pre>
     *   {fileTypeCode}:{assetTypeCode}:{path}:{sizeBytes}:{overwrite}\n
     * </pre>
     * where {@code fileTypeCode} is {@code "i"} (Internal), {@code "l"} (Local)
     * or {@code "c"} (Classpath); {@code assetTypeCode} is the
     * {@code AssetType.code} string (always {@code "b"} for Binary in this
     * version of gdx-teavm); and {@code overwrite} is {@code "0"} or {@code "1"}.
     * The path separator is {@code ":"} and lines end with {@code "\n"}.
     */
    private static void regeneratePreloadTxt(File assetsDir) throws IOException {
        if (!assetsDir.isDirectory()) {
            System.err.println("[BuildForgeTeaVM] WARNING: assets directory not found: " + assetsDir);
            return;
        }
        File preloadTxt = new File(assetsDir, "preload.txt");
        StringBuilder sb = new StringBuilder();
        appendAssets(assetsDir, assetsDir, sb);
        String content = sb.toString();
        Files.writeString(preloadTxt.toPath(), content);
        int lineCount = content.isEmpty() ? 0 : content.split("\n", -1).length;
        System.out.println("[BuildForgeTeaVM] Regenerated preload.txt with " + lineCount + " entries");
    }

    /**
     * Recursively appends preload.txt lines for every regular file under
     * {@code dir} (skipping {@code preload.txt} itself).
     */
    private static void appendAssets(File root, File dir, StringBuilder sb) {
        File[] children = dir.listFiles();
        if (children == null) return;
        for (File child : children) {
            if (child.isDirectory()) {
                appendAssets(root, child, sb);
            } else if (!child.getName().equals("preload.txt")) {
                String relativePath = root.toPath().relativize(child.toPath())
                        .toString().replace('\\', '/');
                long size = child.length();
                // fileType=i (Internal), assetType=b (Binary), path, size, overwrite=1
                // overwrite=1 forces re-download on every page load so that
                // AssetLoadImpl.addAssetToQueue always enqueues the asset even when
                // the file already exists in IndexedDB from a previous download.
                // Without this, assetsCount=0 → progress=NaN → setPreloadReady() never fires.
                sb.append("i:b:").append(relativePath).append(':')
                  .append(size).append(":1\n");
            }
        }
    }
}
