package forge.teavm;

import com.github.xpenatan.gdx.teavm.backends.shared.config.AssetFileHandle;
import com.github.xpenatan.gdx.teavm.backends.shared.config.compiler.TeaCompiler;
import org.teavm.vm.TeaVMOptimizationLevel;

import java.io.File;

/**
 * Build-time driver that invokes the gdx-teavm {@link TeaCompiler} to
 * cross-compile the Forge mobile UI from JVM bytecode into JavaScript for
 * browser deployment.
 *
 * <p>This class runs on the <em>host JVM</em> during the Maven {@code package}
 * phase (triggered by {@code exec-maven-plugin} with the {@code -Pteavm}
 * profile).  It is <strong>not</strong> compiled into the browser bundle – only
 * {@link TeaVMLauncher} and the classes it reaches are transpiled.
 *
 * <h2>Usage</h2>
 * <pre>
 *   mvn -pl forge-gui-teavm -Pteavm package
 * </pre>
 *
 * <h2>Output layout</h2>
 * <pre>
 *   target/dist/webapp/
 *     index.html       – host page generated by WebBackend
 *     forge.js         – transpiled game code
 *     gdx.wasm.js      – LibGDX native code (Emscripten)
 *     assets/          – game resources (copied from assetsDir)
 * </pre>
 *
 * <h2>Iterative debug loop</h2>
 * <ol>
 *   <li>Run this build ({@code mvn -Pteavm package}).</li>
 *   <li>Fix TeaVM compilation errors (typically: missing stubs in
 *       {@code src/main/java/}; see {@link TeaVMAdapter} for the pattern).</li>
 *   <li>Run the smoke test ({@code mvn -Pteavm integration-test}) to verify the
 *       home screen loads in a headless Chromium browser.</li>
 *   <li>Repeat.</li>
 * </ol>
 */
public class BuildForgeTeaVM {

    public static void main(String[] args) {
        /*
         * Path to the Forge assets directory.  The TeaCompiler copies everything
         * under this path into the output webapp/assets/ folder.
         *
         * For a local dev build, resources live in forge-gui/:
         *   assetsDir = "../forge-gui"
         *
         * For CI / release, parameterise via system property:
         *   mvn -Dforge.assetsDir=/path/to/assets -Pteavm package
         *
         * NOTE: The full Forge asset set is multi-gigabyte.  For early
         * development, use a minimal asset set (base skin + core card data only).
         * A CDN / lazy-loading strategy is needed for production deployment.
         */
        String assetsDir = System.getProperty("forge.assetsDir", "../forge-gui");

        /*
         * Output directory.  WebBackend creates a "webapp" sub-folder inside
         * this directory.
         */
        File outputDir = new File("target/dist");

        /*
         * Use ForgeWebBackend instead of bare WebBackend.  ForgeWebBackend
         * overrides setup() to call tool.setStrict(false), which downgrades
         * "missing class/method" diagnostics from hard errors to warnings for
         * code paths that are dead in the browser (Guava caches, threading,
         * java.util.concurrent, javax.xml, etc.).
         */
        ForgeWebBackend backend = new ForgeWebBackend();
        backend.setHtmlTitle("Forge \u2013 Magic: The Gathering");
        // width=0, height=0 → canvas fills the browser window
        backend.setHtmlWidth(0);
        backend.setHtmlHeight(0);
        /*
         * In development: set true to automatically start embedded Jetty
         * after compilation so the game can be tested immediately at
         * http://localhost:8080/.
         *
         * In CI / for HomeScreenLoadTest: set false – the test starts its
         * own HTTP server on a random port.
         */
        backend.setStartJettyAfterBuild(false);

        new TeaCompiler(backend)
                .addAssets(new AssetFileHandle(assetsDir))
                .setMainClass(TeaVMLauncher.class.getName())
                /*
                 * SIMPLE optimisation: faster builds, readable stack traces.
                 * Switch to ADVANCED for release (smaller JS, harder to debug).
                 */
                .setOptimizationLevel(TeaVMOptimizationLevel.SIMPLE)
                .setObfuscated(false)
                .build(outputDir);
    }
}
