package forge.teavm;

import com.github.xpenatan.gdx.teavm.backends.shared.config.AssetFileHandle;
import com.github.xpenatan.gdx.teavm.backends.shared.config.compiler.TeaCompiler;
import com.github.xpenatan.gdx.teavm.backends.web.config.backend.WebBackend;
import org.teavm.vm.TeaVMOptimizationLevel;

import java.io.File;

/**
 * Build-time driver that invokes the gdx-teavm {@link TeaCompiler} to
 * cross-compile the Forge mobile UI from JVM bytecode into JavaScript (or
 * WebAssembly) for browser deployment.
 *
 * <p>This class runs on the <em>host JVM</em> during the Maven {@code package}
 * phase (triggered by {@code exec-maven-plugin} with the {@code -Pteavm}
 * profile).  It is <strong>not</strong> compiled into the browser bundle – only
 * {@link TeaVMLauncher} and the classes it reaches are transpiled.
 *
 * <h2>Usage</h2>
 * <pre>
 *   mvn -pl forge-gui-teavm -Pteavm package
 * </pre>
 *
 * <h2>Output layout</h2>
 * <pre>
 *   target/dist/webapp/
 *     index.html           – host page generated by WebBackend
 *     forge.js             – transpiled game code (JS target)
 *     gdx.wasm.js          – LibGDX native code (Emscripten)
 *     howler.js            – audio library
 *     assets/              – game resources (copied from assetsDir)
 *       res/               – card data, fonts, etc.
 *       ...
 * </pre>
 *
 * <h2>Key open items before this build will succeed</h2>
 * <ol>
 *   <li>The {@code assetsDir} path below must point to a directory that
 *       contains the full Forge {@code res/} tree.  For development this is
 *       typically {@code ../forge-gui/} relative to this module.</li>
 *   <li>The API incompatibilities listed in {@link TeaVMAdapter} and in
 *       {@code pom.xml} must be resolved before the TeaCompiler step
 *       completes without errors.</li>
 *   <li>LibGDX must be bumped to 1.14.0 across all modules (see
 *       {@code pom.xml}).</li>
 * </ol>
 */
public class BuildForgeTeaVM {

    public static void main(String[] args) {
        /*
         * Path to the Forge assets directory.  The TeaCompiler copies
         * everything under this directory into the output webapp/assets/
         * folder.
         *
         * For a local development build the resources live in forge-gui/:
         *   assetsDir = "../forge-gui"
         *
         * For a CI / release build the path should be parameterised via a
         * system property or Maven resource filtering so it can be configured
         * externally:
         *   assetsDir = System.getProperty("forge.assetsDir", "../forge-gui")
         */
        String assetsDir = System.getProperty("forge.assetsDir", "../forge-gui");

        /*
         * Output directory for the compiled web application.
         * The WebBackend creates a "webapp" sub-folder inside this directory
         * containing index.html, forge.js, gdx.wasm.js, howler.js and assets/.
         */
        File outputDir = new File("target/dist");

        WebBackend backend = new WebBackend()
                // Title shown in the browser tab / generated index.html
                .setHtmlTitle("Forge – Magic: The Gathering")
                // Dimensions are 0/0 so the canvas fills the browser window
                .setHtmlWidth(0)
                .setHtmlHeight(0)
                /*
                 * Set to true during development to automatically start an
                 * embedded Jetty server after compilation so the game can be
                 * tested immediately at http://localhost:8080/.
                 * Set to false for CI / release builds.
                 */
                .setStartJettyAfterBuild(false);

        new TeaCompiler(backend)
                /*
                 * Add the Forge assets directory.  All files it contains are
                 * copied verbatim into the output webapp/assets/ folder and
                 * pre-loaded by the browser before the game starts.
                 *
                 * NOTE: The full Forge asset set is many gigabytes in size.
                 * For a practical browser deployment a selective asset list
                 * (base skin + card image CDN lazy-loading) will be needed.
                 * See the "Asset bundling" section in pom.xml for discussion.
                 */
                .addAssets(new AssetFileHandle(assetsDir))
                /*
                 * TeaVMLauncher is the browser-side entry point.  The
                 * TeaCompiler performs reachability analysis from this class and
                 * compiles every class it can reach.
                 */
                .setMainClass(TeaVMLauncher.class.getName())
                /*
                 * Use SIMPLE optimisation during development for faster builds
                 * and better stack traces.  Switch to ADVANCED for release
                 * builds to reduce the output JS size.
                 */
                .setOptimizationLevel(TeaVMOptimizationLevel.SIMPLE)
                /*
                 * Keep symbols readable during development.  Set to true for
                 * release builds (reduces JS size but makes debugging harder).
                 */
                .setObfuscated(false)
                .build(outputDir);
    }
}
